[tool.poetry]
name = "project1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.2.1"
datasets = "^2.18.0"
evaluate = "^0.4.1"
scikit-learn = "^1.4.1.post1"
accelerate = "^0.27.2"
transformers = "^4.38.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
