[tool.poetry]
name = "project2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.2.1"
bitsandbytes = "^0.42.0"
accelerate = "^0.27.2"
transformers = "^4.38.2"
peft = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
