[tool.poetry]
name = "test1"
version = "0.1.0"
description = ""
authors = ["lukaskellerstein"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.10"
matplotlib = "^3.7.0"
numpy = "^1.24.2"
pandas = "^1.5.3"
tensorflow = "2.10.0"
scikit-learn = "^1.2.1"
openpyxl = "^3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
