[tool.poetry]
name = "autogen-llm-0"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.8"
autogen-agentchat = "^0.4.4"
autogen-ext = {extras = ["azure"], version = "^0.4.4"}
python-dotenv = "^1.0.1"
asyncio = "^3.4.3"
tiktoken = "^0.8.0"
openai = "^1.60.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
