[tool.poetry]
name = "project1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.178"
openai = "^0.27.7"
google-search-results = "^2.4.2"
huggingface-hub = "^0.14.1"
python-dotenv = "^1.0.0"
asyncio = "^3.4.3"
playwright = "^1.35.0"
beautifulsoup4 = "^4.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
