[tool.poetry]
name = "autogen-magentic-one-1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.8"
autogen-agentchat = "^0.4.7"
autogen-ext = {extras = ["magentic-one", "openai"], version = "^0.4.7"}
python-dotenv = "^1.0.1"
asyncio = "^3.4.3"
langchain-experimental = "^0.3.4"
langchain-community = "^0.3.17"
pandas = "^2.2.3"
numpy = "^2.2.3"
matplotlib = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
