[tool.poetry]
name = "autogen-team"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.8"
autogen-agentchat = "^0.4.7"
autogen-ext = {extras = ["openai"], version = "^0.4.7"}
python-dotenv = "^1.0.1"
asyncio = "^3.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
