[tool.poetry]
name = "test1"
version = "0.1.0"
description = ""
authors = ["lukaskellerstein"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.6"
matplotlib = "^3.7.0"
numpy = "^1.24.2"
pandas = "^1.5.3"
tensorflow = "2.10.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
