[project]
name = "0-simplest"
version = "0.1.0"
description = ""
authors = [
    {name = "lukaskellerstein",email = "lukas.kellerstein@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat (>=0.4.8.1,<0.5.0.0)",
    "asyncio (>=3.4.3,<4.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "autogen-ext[openai] (>=0.4.8.1,<0.5.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
